<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="EUC-KR">
<title>Insert title here</title>
</head>
<body>
	<table border="1">
		<thead>
			<tr>
				<th>하나</th>
				<th>둘</th>
				<th>셋</th>
				<th>넷</th>
				<th>다섯</th>
				<th>여섯</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>7</td>
				<td>13</td>
				<td>19</td>
				<td>25</td>
				<td>31</td>
			</tr>
			<tr>
				<td>2</td>
				<td>8</td>
				<td>14</td>
				<td>20</td>
				<td>26</td>
				<td>32</td>
			</tr>
			<tr>
				<td>3</td>
				<td>9</td>
				<td>15</td>
				<td>21</td>
				<td>27</td>
				<td>33</td>
			</tr>
			<tr>
				<td>4</td>
				<td>10</td>
				<td>16</td>
				<td>22</td>
				<td>28</td>
				<td>34</td>
			</tr>
			<tr>
				<td>5</td>
				<td>11</td>
				<td>17</td>
				<td>23</td>
				<td>29</td>
				<td>35</td>
			</tr>
			<tr>
				<td>6</td>
				<td>12</td>
				<td>18</td>
				<td>24</td>
				<td>30</td>
				<td>36</td>
			</tr>
		</tbody>
	</table>
</body>
</html>